name: HTML CI

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check HTML file
        run: |
          if grep -q "<html>" index.html
          then
            echo "HTML test passed!"
          else
            echo "HTML test failed!"
            exit 1
          fi

      - name: Check HTML title
        run: |
          if grep -q "<title>" index.html
          then
            echo "Title test passed!"
          else
            echo "Title test failed!"
            exit 1
          fi